# Generated by Django 2.2.13 on 2020-07-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0004_fix_types_and_indices"),
    ]

    operations = [
        migrations.RenameModel(old_name="EveNameCache", new_name="EveEntity",),
    ]
