# Generated by Django 3.1.10 on 2021-05-11 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("standingsrequests", "0006_add_user_to_revocations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=254)),
                ("standing", models.FloatField(db_index=True)),
                ("is_watched", models.BooleanField(default=False)),
                (
                    "contact_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="standingsrequests.contactset",
                    ),
                ),
                (
                    "eve_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standingrequests_contact",
                        to="eveuniverse.eveentity",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="alliancecontact",
            name="contact_set",
        ),
        migrations.RemoveField(
            model_name="alliancecontact",
            name="labels",
        ),
        migrations.RemoveField(
            model_name="charactercontact",
            name="contact_set",
        ),
        migrations.RemoveField(
            model_name="charactercontact",
            name="labels",
        ),
        migrations.RemoveField(
            model_name="corporationcontact",
            name="contact_set",
        ),
        migrations.RemoveField(
            model_name="corporationcontact",
            name="labels",
        ),
        migrations.DeleteModel(
            name="EveEntity",
        ),
        migrations.AlterField(
            model_name="contactlabel",
            name="contact_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="standingsrequests.contactset",
            ),
        ),
        migrations.DeleteModel(
            name="AllianceContact",
        ),
        migrations.DeleteModel(
            name="CharacterContact",
        ),
        migrations.DeleteModel(
            name="CorporationContact",
        ),
        migrations.AddField(
            model_name="contact",
            name="labels",
            field=models.ManyToManyField(
                related_name="contacts", to="standingsrequests.ContactLabel"
            ),
        ),
    ]
