# Generated by Django 3.1.10 on 2021-05-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0007_auto_20210511_0049"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
    ]
