# Generated by Django 3.1.10 on 2021-05-12 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("standingsrequests", "0007_big_overhaul"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteraffiliation",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="character_affiliation",
                serialize=False,
                to="eveuniverse.eveentity",
            ),
        ),
    ]
