# Generated by Django 3.1.10 on 2021-05-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("standingsrequests", "0008_auto_20210512_1334"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporationAffiliation",
            fields=[
                (
                    "corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="corporation_affiliation",
                        serialize=False,
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "alliance",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="+",
                        to="eveuniverse.eveentity",
                    ),
                ),
            ],
        ),
    ]
