# Generated by Django 3.1.10 on 2021-05-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0008_remove_contact_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CharacterAssociation",
        ),
    ]
