# Generated by Django 3.2.9 on 2021-12-20 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import standingsrequests.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("standingsrequests", "0009_make_ceo_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="standingrequest",
            name="reason",
            field=models.CharField(
                choices=[
                    ("NO", "None recorded"),
                    ("OR", "Requested by character owner"),
                    ("LP", "Character owner has lost permission"),
                    ("CT", "Not all corp tokens are recorded in Auth."),
                    ("RG", "Standing has been revoked in game"),
                    ("SG", "Already has standing in game"),
                ],
                default="NO",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="standingrevocation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("NO", "None recorded"),
                    ("OR", "Requested by character owner"),
                    ("LP", "Character owner has lost permission"),
                    ("CT", "Not all corp tokens are recorded in Auth."),
                    ("RG", "Standing has been revoked in game"),
                    ("SG", "Already has standing in game"),
                ],
                default="NO",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="RequestLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("CN", "confirmed"), ("RJ", "rejected")], max_length=2
                    ),
                ),
                ("is_action_automatic", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NO", "None recorded"),
                            ("OR", "Requested by character owner"),
                            ("LP", "Character owner has lost permission"),
                            ("CT", "Not all corp tokens are recorded in Auth."),
                            ("RG", "Standing has been revoked in game"),
                            ("SG", "Already has standing in game"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("RQ", "request"), ("RV", "revocation")], max_length=2
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                (
                    "action_by",
                    models.ForeignKey(
                        help_text="User who performed the action. None means the action was performed automatically by the app.",
                        null=True,
                        on_delete=models.SET(
                            standingsrequests.models.get_or_create_sentinel_user
                        ),
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=models.SET(
                            standingsrequests.models.get_or_create_sentinel_user
                        ),
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "request log",
                "verbose_name_plural": "request log",
            },
        ),
    ]
