# Generated by Django 3.1.10 on 2021-05-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("standingsrequests", "0010_characterassociation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterassociation",
            name="main_character",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_association",
                to="eveuniverse.eveentity",
            ),
        ),
    ]
