# Generated by Django 3.2.9 on 2021-12-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0010_requestlogentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestlogentry",
            old_name="requested_on",
            new_name="requested_at",
        ),
    ]
