# Generated by Django 3.2.9 on 2021-12-21 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import standingsrequests.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("standingsrequests", "0010_add_request_log"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestlogentry",
            name="contact",
        ),
        migrations.AddField(
            model_name="requestlogentry",
            name="requested_for",
            field=models.ForeignKey(
                help_text="Alt character or corporation to change standing for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eveuniverse.eveentity",
            ),
        ),
        migrations.CreateModel(
            name="FrozenMain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alliance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveuniverse.eveentity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.SET(
                            standingsrequests.models.get_or_create_sentinel_user
                        ),
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="requestlogentry",
            name="action_by",
            field=models.ForeignKey(
                help_text="Main who performed the action. None means the action was performed automatically by the app.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="standingsrequests.frozenmain",
            ),
        ),
        migrations.AlterField(
            model_name="requestlogentry",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="standingsrequests.frozenmain",
            ),
        ),
    ]
