# Generated by Django 3.1.10 on 2021-05-12 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("standingsrequests", "0010_auto_20210512_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteraffiliation",
            name="faction",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eveuniverse.eveentity",
            ),
        ),
    ]
