# Generated by Django 3.2.9 on 2021-12-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0011_rename_requested_on_requestlogentry_requested_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requestlogentry",
            options={
                "verbose_name": "request log",
                "verbose_name_plural": "request log",
            },
        ),
    ]
