# Generated by Django 3.2.9 on 2021-12-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0012_auto_20211221_1840"),
    ]

    operations = [
        migrations.AddField(
            model_name="frozenalt",
            name="category",
            field=models.CharField(
                choices=[("CH", "character"), ("CP", "corporation")],
                default="CH",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
