# Generated by Django 3.1.10 on 2021-05-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0014_auto_20210105_1413"),
        ("standingsrequests", "0012_auto_20210511_1944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characteraffiliation",
            name="main_character",
        ),
        migrations.AddField(
            model_name="characteraffiliation",
            name="eve_character",
            field=models.ForeignKey(
                default=None,
                help_text="Related auth character (if any)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eveonline.evecharacter",
            ),
        ),
    ]
