# Generated by Django 3.1.10 on 2021-05-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0014_auto_20210105_1413"),
        ("eveuniverse", "0005_type_materials_and_sections"),
        ("standingsrequests", "0013_auto_20210511_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteraffiliation",
            name="alliance",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eveuniverse.eveentity",
            ),
        ),
        migrations.AlterField(
            model_name="characteraffiliation",
            name="eve_character",
            field=models.ForeignKey(
                default=None,
                help_text="Related auth character (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eveonline.evecharacter",
            ),
        ),
    ]
