# Generated by Django 3.2.9 on 2021-12-19 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0013_remove_requestlogentry_is_user_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlogentry",
            name="action_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
