# Generated by Django 3.2.9 on 2021-12-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0014_requestlogentry_action_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlogentry",
            name="action",
            field=models.CharField(
                choices=[("CN", "confirmed"), ("RJ", "rejected")], max_length=2
            ),
        ),
    ]
