# Generated by Django 3.2.9 on 2021-12-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0015_alter_requestlogentry_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestlogentry",
            name="action_at",
        ),
    ]
