# Generated by Django 3.2.9 on 2021-12-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0016_remove_requestlogentry_action_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlogentry",
            name="reason",
            field=models.CharField(
                choices=[
                    ("NO", "None recorded"),
                    ("OR", "Requested by character owner"),
                    ("LP", "Character owner has lost permission"),
                    ("CT", "Not all corp tokens are recorded in Auth."),
                    ("RG", "Standing has been revoked in game"),
                ],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
    ]
