# Generated by Django 3.2.9 on 2021-12-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0017_alter_requestlogentry_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlogentry",
            name="contact_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestlogentry",
            name="contact_type",
            field=models.CharField(
                choices=[("character", "character"), ("corporation", "corporation")],
                default="character",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
