# Generated by Django 3.2.9 on 2021-12-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0018_auto_20211220_1637"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlogentry",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("alliance", "alliance"),
                    ("character", "character"),
                    ("constellation", "constellation"),
                    ("corporation", "corporation"),
                    ("faction", "faction"),
                    ("inventory_type", "inventory_type"),
                    ("region", "region"),
                    ("solar_system", "solar_system"),
                    ("station", "station"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
