# Generated by Django 3.2.9 on 2021-12-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0019_alter_requestlogentry_contact_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestlogentry",
            old_name="contact_type",
            new_name="contact_category",
        ),
    ]
