# Generated by Django 3.2.9 on 2021-12-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "standingsrequests",
            "0020_rename_contact_type_requestlogentry_contact_category",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestlogentry",
            old_name="action_by",
            new_name="approver_character_name",
        ),
        migrations.RenameField(
            model_name="requestlogentry",
            old_name="requested_by",
            new_name="requestor_character_name",
        ),
        migrations.AddField(
            model_name="requestlogentry",
            name="approver_corporation_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestlogentry",
            name="requestor_corporation_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
