# Generated by Django 3.2.9 on 2021-12-20 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0005_type_materials_and_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("standingsrequests", "0021_auto_20211220_1705"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestlogentry",
            name="approver_character_name",
        ),
        migrations.RemoveField(
            model_name="requestlogentry",
            name="approver_corporation_name",
        ),
        migrations.RemoveField(
            model_name="requestlogentry",
            name="contact_category",
        ),
        migrations.RemoveField(
            model_name="requestlogentry",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="requestlogentry",
            name="requestor_character_name",
        ),
        migrations.RemoveField(
            model_name="requestlogentry",
            name="requestor_corporation_name",
        ),
        migrations.AddField(
            model_name="requestlogentry",
            name="action_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="requestlogentry",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eveuniverse.eveentity",
            ),
        ),
        migrations.AddField(
            model_name="requestlogentry",
            name="request_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
