# Generated by Django 3.2.9 on 2021-12-20 20:55

from django.conf import settings
from django.db import migrations, models

import standingsrequests.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("standingsrequests", "0022_auto_20211220_1903"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlogentry",
            name="is_action_automatic",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="requestlogentry",
            name="action_by",
            field=models.ForeignKey(
                help_text="User who performed the action. None means the action was performed automatically by the app.",
                null=True,
                on_delete=models.SET(
                    standingsrequests.models.get_or_create_sentinel_user
                ),
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requestlogentry",
            name="request_by",
            field=models.ForeignKey(
                on_delete=models.SET(
                    standingsrequests.models.get_or_create_sentinel_user
                ),
                related_name="+",
                to="auth.user",
            ),
        ),
    ]
