# Generated by Django 3.2.9 on 2021-12-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0024_auto_20211220_2145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlogentry",
            name="reason",
            field=models.CharField(
                choices=[
                    ("NO", "None recorded"),
                    ("OR", "Requested by character owner"),
                    ("LP", "Character owner has lost permission"),
                    ("CT", "Not all corp tokens are recorded in Auth."),
                    ("RG", "Standing has been revoked in game"),
                    ("SG", "Already has standing in game"),
                ],
                max_length=2,
            ),
        ),
    ]
