# Generated by Django 3.2.9 on 2021-12-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standingsrequests", "0025_alter_requestlogentry_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestlogentry",
            old_name="request_by",
            new_name="requested_by",
        ),
    ]
